apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: actual
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-finance
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift
    repoURL: https://github.com/jkeam/actual.git
    targetRevision: dev
    kustomize:
      namespace: app-finance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
