apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: apps-helm-repo
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: apps-helm-repo
    repoURL: https://github.com/jkeam/lab-lan-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
