apiVersion: v1
kind: Namespace
metadata:
  name: hello-go
  annotations:
    openshift.io/description: "App to say hello"
    openshift.io/display-name: "Hello Go"
  labels:
    kubernetes.io/metadata.name: hello-go
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-admin
  namespace: hello-go
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: hello-go
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-go
  source:
    chart: hello-go
    repoURL: https://keamchart.com
    targetRevision: 0.0.1
    helm:
      releaseName: hello-go
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
