apiVersion: v1
kind: Namespace
metadata:
  name: nibbler-claw

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-admin
  namespace: nibbler-claw
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nibbler-claw
  namespace: openshift-gitops
spec:
  destination:
    namespace: nibbler-claw
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openclaw/nibbler
    repoURL: https://github.com/jkeam/lab-lan-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
