apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: finance
  namespace: openshift-gitops
spec:
  destination:
    namespace: finance
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/db
    repoURL: https://github.com/jkeam/finance-web.git
    targetRevision: main
    kustomize:
      namespace: finance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
